### ISSUE TITLE
Improve Mac OS X Compatibility on shellcraft

### ISSUE THREAD

**Issue by aluex** [binjitsu/binjitsu#12]
Apple has shipped a bundle of special cctools where 'as' does not accept long argument like '--version'

    % shellcraft i386.linux.sh
    Traceback (most recent call last):
    ...
    subprocess.CalledProcessError: Command '['/usr/bin/as', '--version', '/dev/null']' returned non-zero exit status 1

    % /usr/bin/as --version
    FATAL:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../libexec/as/x86_64/as: I don't understand '-' flag!

**Comment by zachriggle** [comment]
For OSX we require that our custom Binutils is installed:

http://docs.pwntools.com/en/latest/install/binutils.html
https://github.com/Gallopsled/pwntools-binutils
https://github.com/Gallopsled/pwntools-binutils/tree/master/osx

**Comment by aluex** [comment]
Thanks :+1:
