### ISSUE TITLE
SigReturnFrame.get_frame(...) should not exist

### ISSUE THREAD

**Issue by zachriggle** [binjitsu/binjitsu#29]
I'm not sure of the purpose behind `get_frame`.

It should not need to exist, `__str__` should do absolutely everything that's necessary.  If additional configuration is required, it should be passed into the contructor (`__init__`) with sane defaults.

https://github.com/binjitsu/binjitsu/blob/master/pwnlib/rop/srop.py#L223

**Comment by eQu1NoX** [comment]
Fixed at https://github.com/eQu1NoX/binjitsu/commit/f74da470d3fac1cc7b8f6a52968067970eb97197
