### ISSUE TITLE
.interactive() is broken when a process over ssh tube execve's another process.

### ISSUE THREAD

**Issue by borski** [binjitsu/binjitsu#3]
If you run ssh into a box and run a process that then ends up execve'ing another process, p.interactive() just hangs infinitely. Running in DEBUG mode it supposedly sends the data, but nothing is ever received or printed to the screen other than the DEBUG sent data.

**Comment by borski** [comment]
Looks like this got fixed by b9ac583e8abaaa967c6a8da73037021ce23f5bf1, and I verified it.

**Comment by zachriggle** [comment]
Thanks for reporting! :smile:
