### ISSUE TITLE
SigReturnFrame(...) doctests are broken

### ISSUE THREAD

**Issue by zachriggle** [binjitsu/binjitsu#30]
See the skipped tests in SigReturnFrame here:

https://github.com/binjitsu/binjitsu/blob/master/pwnlib/rop/srop.py#L82

**Comment by eQu1NoX** [comment]
Hm could this be because context.arch and context.clear were removed? I'll add them in.

**Comment by eQu1NoX** [comment]
Hm. This is a weird bug.
https://travis-ci.org/binjitsu/binjitsu/builds/66854062

**Comment by eQu1NoX** [comment]
Fixed at https://github.com/binjitsu/binjitsu/commit/3a63c0804d36cea1f9ac96050a9476932662c964
