### ISSUE TITLE
Arm arch not Found

### ISSUE THREAD

**Issue by iN3O** [binjitsu/binjitsu#68]
on running 

> asm("mov r0, #SYS_select", arch = 'arm', os = 'linux', bits=32)

its giving me following error.

> Could not find 'as' installed for ContextType(arch = 'arm', bits = 32, endian = 'little', os = 'linux'

**Comment by zachriggle** [comment]
You need to install an assembler for ARM.

https://binjitsu.readthedocs.org/install/binutils.html
