### ISSUE TITLE
ROP: setRegisters is too strict in looking for gadgets

### ISSUE THREAD

**Issue by toomanybananas** [binjitsu/binjitsu#75]
When using setRegisters to set the contents of a ROP chain, it will look for gadgets of the form `pop [r32/64]; ret`, ignoring gadgets such as `pop rax; pop rbx; ret`.

Currently, it uses find_gadget to look for the gadget, but it could probably use search() instead.

Reproduction:
```
 #!/usr/bin/env python2
from pwn import *
context.arch = 'amd64'
e = ELF.from_assembly("pop rax; pop rbx; ret")
rop = ROP(e)
print rop.gadgets
rop.setRegisters({"rax":1337})
print rop.dump()
```

**Comment by zachriggle** [comment]
Yep, `setRegisters` is currently dumb.  There's a bunch of work that @lieanu did last summer which uses Amoco for symbolic evaluation of ROP gadgets and handles this case (and many crazier cases).
