### ISSUE TITLE
consider git tagging a release/version

### ISSUE THREAD

**Issue by anthraxx** [binjitsu/binjitsu#79]
Hey, I would really love to see a release tag (and possibly periodically some more tags in future).
This would really aid to create a static package out of this cool project :smile:

**Comment by zachriggle** [comment]
The problem with release tags is that every commit has roughly the same level of testing, and I commit [most days](https://github.com/binjitsu/binjitsu/graphs/commit-activity) of the week.

Any release would just be dated (e.g. v2016.05.31).  If that meets your needs, I can do that :).

**Comment by anthraxx** [comment]
sure, move fast and break things :see_no_evil: :smiling_imp:
For me its stable enough... I just would be glad if you can do such tags regularly, you still have a bit more feeling when things work more like just an arbitrary commit :smiley_cat:

**Comment by zachriggle** [comment]
Tagged 3.0.0 release
